{% set name = "maven" %}
{% set version = "3.9.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://dlcdn.apache.org/maven/maven-3/{{ version }}/binaries/apache-maven-{{ version }}-bin.tar.gz
  sha256: 7a9cdf674fc1703d6382f5f330b3d110ea1b512b51f1652846d9e4e8a588d766

build:
  number: 0
  skip: true  # [s390x]

requirements:
  run:
    - openjdk

test:
  commands:
    - mvn -v

about:
  home: https://maven.apache.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A software project management and comprehension tool.
  description: |
    Apache Maven is a software project management and comprehension tool.
    Based on the concept of a project object model (POM), Maven can manage
    a project's build, reporting and documentation from a central piece of information.
  dev_url: https://github.com/apache/maven
  doc_url: https://maven.apache.org/guides/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - hadim
