travis:
  secure:
    BINSTAR_TOKEN: m1MLP3kp3b0VsQDBKPfb/GRoaEMlNdHyKwaVbJEidzMzL3JWYXtDy4ufX/scR+cL9CTg7Id7biXsk8KY3Y/8Ji5CIEubRITzUiIP6MwCqoR/WOS5JTOltjdDxzg2UejNtIakLPRbv0o7p8NmcnBnptk2enY2/Vg0TPqm9LBwBcAdIHsrH0cNghuaeODMLXT6KcKIBsDyvKqP7RaIoBuoqGz1utkXbP6Lr4wtvF8WKHDbNefnMF/qihkGQ649W10JErZbdS9fFX8ORPWCUoRg3yirBEmneBfqyrzf3kLxLVm9P6FO4AbJHcSctx+6cbZX9H4d79udrJQB2OdLvKbrHcmEdh6GJTnA/oLxozPBr131V2JJ6zDwlhy3rcTEoH+nuHmf3P0pGIqxI/+Zj1ZMdzOL8mzIEwAm8VdBsqTsO6lo2jFwCzUjASzQcEltHdUaHNVpydiGzy2MtnU7G4oqtqmN3tc4ATZh9gWxTOeK4xUDioucPy/kh6cPY7S8wElj/gp+pnPGyjGb2hLzHWtzxNCgAL58b+xqY0hmVlMygIPHuPQHUwvA+w/GPtFswp4lG0SemErdphs17+0N3MClcsDUTP3pKSW1sDgnbBXxaU2vTv0WvPq869QThCkmIluw5x1+TYZ59RudwvjZ4q6I3/U1qfvEKR/Pncu5ivSniGM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
