travis:
  secure:
    BINSTAR_TOKEN: 9TfhImQwtCOUfSo3uD0xCxBvRyCodAh/Opaz4whFR7BKH9Z+z0F7kpziYcsE73AVq4izYNhO4DlLX/CRynh5kHb5oEFF9TJUzPVDaxmwByHoSLX6jCtE2nG/3FRp4b8sbKN1uqN4zt+3J3VH5dRwjmJFOtwyT8S04HLhHKEbGQt4iUhBCcBWAPMnXCO8pMgPPAutnUfZRLoH2MNBBVk4vPXPMA9emTa5VE2jKIxQJ3cZvrsD59TwXXVFl8dV4cObC0sA9OgXXMmCbpSiWltiVAbl2rrjvU0FnMbsboq70ObwIDL5TKS3y8TEmmL8TS2foIr3ZCLsJEH4put4PDLFqLyHi4heDqNLHxnqWPZavbRHLdgGBBWPCkER9IJlub56PbnBP3v6ojyIa+TCNiLGffqzRXbC5tk9xHyI8QDY2b5FnANTAjQmFMfkD7zWzxj801aNdFLxwGp5gwJgxNo94c35qD8E/UDM+pAsfrstahEnxkvQiD5SfKSbAS7osud2nxsoq74ck4OJFVkZhrokf9s7vN1Zjkcj3IPSfDfzA3w1oyGipR3fllNpjtxo2GeRTHZpTNlUddLkEaDWKh2xXbHTVG6jpaW0qjcq45cQWNa3poWMznTyKrejWpCh0xsrCe4g/coii1R0xeK9WgyHWk59dgn1IN/GLaeKCQ8+XEc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
